// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122080738_DataAnnotations")]
    partial class DataAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CarbohydrateGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EnergyKcal")
                        .HasColumnType("int");

                    b.Property<decimal?>("FatGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProteinGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaltGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("FoodRecords");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodRecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("FoodRecordId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("FoodRecordId");

                    b.ToTable("FoodRecordItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.HealthConsultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("HealthConsultants");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressurePulse")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SugarLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthConsultantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthConsultantId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodRecord", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patient", "Patient")
                        .WithMany("FoodRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodRecordItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.FoodItem", "FoodItem")
                        .WithMany("FoodRecordItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.FoodRecord", null)
                        .WithMany("FoodRecordItems")
                        .HasForeignKey("FoodRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.MedicalRecord", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patient", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.HealthConsultant", "HealthConsultant")
                        .WithMany("Patients")
                        .HasForeignKey("HealthConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthConsultant");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodItem", b =>
                {
                    b.Navigation("FoodRecordItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.FoodRecord", b =>
                {
                    b.Navigation("FoodRecordItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.HealthConsultant", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patient", b =>
                {
                    b.Navigation("FoodRecords");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
